name: api
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env.docker
    ports:
      - 8080:8080
    networks:
      - app
    restart: always
    depends_on:
      database:
        condition: service_healthy
    # volumes:
    #   - .:/app/api
    stop_grace_period: 5m

  database:
    image: postgres:17.5
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: u
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - app
    volumes:
      - ./dbdata/lib/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  app:
    driver: bridge
