services:
  App\EventSubscriber\TokenSubscriber:
    public: true
    arguments:
      - '@App\Service\TokenService'
    tags:
      - {name: kernel.event_subscriber}
  App\Controller\Users\UserAutenticatedController:
    public: true
    tags: ['controller.service_arguments']
  _defaults:
    autowire: true
    autoconfigure: true
  App\Service\TokenService:
    arguments:
      $jwtSecret: '%env(JWT_SECRET)%'
